apiVersion: v1
kind: Service
metadata:
  name: expense-api
  namespace: expense-dev
  labels:
    app.kubernetes.io/name: expense-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: expense-tracking
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: expense-api
  ports:
    - name: http
      port: 8080
      targetPort: http
