apiVersion: v1
kind: Secret
metadata:
  name: expense-api-secrets
  namespace: expense-dev
  labels:
    app.kubernetes.io/name: expense-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: expense-tracking
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: replace-at-apply-time-from-secrets-manager
  SPRING_REDIS_PASSWORD: replace-at-apply-time-from-secrets-manager
  SPRING_KAFKA_SASL_PASSWORD: replace-at-apply-time-from-secrets-manager
