apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: expense-api
  namespace: expense-dev
  labels:
    app.kubernetes.io/name: expense-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: expense-tracking
    app.kubernetes.io/managed-by: kubectl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expense-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
      selectPolicy: Min
