apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: expense-api
  namespace: expense-dev
  labels:
    app.kubernetes.io/name: expense-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: expense-api
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
