apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-api
  namespace: expense-dev
  labels:
    app.kubernetes.io/name: expense-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: expense-tracking
    app.kubernetes.io/managed-by: kubectl
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: expense.dev.uptimecrew.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-api
                port:
                  number: 8080
